### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by reaperhulk** [pypa/wheel#363]
`wheel` moved to `packaging` in https://github.com/pypa/wheel/pull/346 but hasn't done a release since. That switch means `abi3` tags on Windows will now work, so it'd be great to see a release soon! Thanks for the work on this project 😄

**Comment by agronholm** [comment]
I suppose I could cut a release real soon. I've been pretty wrapped up in the 1.0 work and my other projects.

**Comment by agronholm** [comment]
I did a last minute check and it seems like the ABI tag generation for pypy2 is wrong. It gives `pp27u` where it should give `pypy_41`. Can't release until this is fixed.

**Comment by mattip** [comment]
Can you point to a test that generates that tag?

**Comment by agronholm** [comment]
Run `tox -e pypy`.

**Comment by agronholm** [comment]
If you look at `get_abi_tag()`, it just blindly slaps the interpreter version after `pp`.

**Comment by agronholm** [comment]
Oddly enough, pypy3 seems to be fine with that (`pypy36_pp73`).

**Comment by mattip** [comment]
`tox -e pypy` says no pypy can be found. How do I tell it where my pypy is?

**Comment by agronholm** [comment]
You need to have `pypy` in your `PATH`.

**Comment by mattip** [comment]
hmm, I thought I fixed the `get_config_var('SOABI')` for the last release :(

**Comment by agronholm** [comment]
I bear some responsibility too for failing to add PyPy2 to the test matrix.

**Comment by agronholm** [comment]
I'm currently not understanding how it still gets the old ABI tag from `get_abi_tag()`. I will investigate.

**Comment by mattip** [comment]
yeah, that works fine. It returns 'pypy_73' which is correct.

**Comment by agronholm** [comment]
Oohh...it's because of `from distutils.sysconfig import get_config_var`. If that is replaced with `from sysconfig import get_config_var`, it gives the correct result.

**Comment by mattip** [comment]
sounds like a bug in the released stdlib :(

**Comment by agronholm** [comment]
Well, I ran the test suite against all the interpreters and everything passed. Good enough for me :)

**Comment by mattip** [comment]
I think `sysconfig` is supposed to be preferred over `distutils.sysconfig`. Sorry I missed that in PR #346

**Comment by agronholm** [comment]
No problem. All's well that ends well.

**Comment by agronholm** [comment]
Released v0.35.0.

**Comment by reaperhulk** [comment]
Thanks @agronholm, much appreciated!
