### ISSUE TITLE
wheel 0.36.0 fails on macOS 11 (Big Sur) when MACOSX_DEPLOYMENT_TARGET=11

### ISSUE THREAD

**Issue by fxcoudert** [pypa/wheel#385]
On previously macOS versions, the major version were 10.15, 10.14, etc. But on macOS Big Sur (11.x.y) the major version is now 11, and the next major version will be 12, etc.

Therefore, because `MACOSX_DEPLOYMENT_TARGET` typically specifies a major macOS version, it is now natural to have `MACOSX_DEPLOYMENT_TARGET=11`. This is accepted by all system build tools and compilers.

This triggered several build failures in cpython 3.9.0, which are now fixed (see https://github.com/python/cpython/pull/23556). This is also triggering problems now in wheel. We are seeing this error as part of Homebrew build and testing (https://github.com/Homebrew/homebrew-core/pull/66063#issuecomment-737538309).

---

I install Python 3.9.0, with an upstream patch (https://github.com/python/cpython/pull/23556), and wheel 0.36.0. Then I run `pip3 install markupsafe`, which gives the following error:

```
    File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 337, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 260, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 52, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/usr/local/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
      assert len(base_version) == 2
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for markupsafe
```

**Comment by fxcoudert** [comment]
What's happening? `calculate_macosx_platform_tag` is called with `platform_tag` being `macosx-11-x86_64`. Therefore `base_version` becomes `(11, )`, and this triggers the assert on line 356. I'm not actually sure why that assert is there, it seems contradictory with the check on `len(base_version)` above.

Even if we remove that assert, or the platform_tag were different: if `MACOSX_DEPLOYMENT_TARGET=11` is set in the environment, then the code below will set `base_version` to `deploy_target`, which will be `(11, )`. That's not wrong, but it will trigger another assert on line 371.

**Comment by fxcoudert** [comment]
On further thought, I think since `distutils.util.get_platform()` returns `macosx-11-x86_64`, the platform tag should be `macosx_11_x86_64` according to PEP 425.

**Comment by agronholm** [comment]
@Czaki comments? It's your code.

**Comment by agronholm** [comment]
Also, how come the existing tests don't fail when run on macOS 11? Does this only happen when the env variable is set?

**Comment by fxcoudert** [comment]
@agronholm I don't know how you run your tests. This happens when `MACOSX_DEPLOYMENT_TARGET=11` at runtime, or when Python was built with `MACOSX_DEPLOYMENT_TARGET=11`.

**Comment by Czaki** [comment]
@fxcoudert could You check `MACOSX_DEPLOYMENT_TARGET=11.0`? Every time when I work with `MACOSX_DEPLOYMENT_TARGET` I set `<mayor>.<minor>`. 

I also check pypi warehouse source code: https://github.com/pypa/warehouse/blob/0b6c95b1318a1572507d33f8abf220eef2984b19/warehouse/forklift/legacy.py#L127 and its requirements to have mayor and minor provided. So tag should be `macosx_11_0_x86_64`

I do not upgrade to BigSur yet. 

When I working on this code there is no option to build a wheel for the system below 10.6. So I do not expect to provide only major version.

**Comment by fxcoudert** [comment]
@Czaki the numbering of macOS has changed from `10.major.minor` to `major.minor.minor2`. Like you said, it is usual (but not mandatory) to set `MACOSX_DEPLOYMENT_TARGET` to the major macOS version: before, that was `10.15`, `10.14`, etc. Now it is `11`, and the next major version will be `12`.

In any case, `MACOSX_DEPLOYMENT_TARGET=11` is valid and should not lead to failure.

**Comment by Czaki** [comment]
> @Czaki the numbering of macOS has changed from `10.major.minor` to `major.minor.minor2`. Like you said, it is usual (but not mandatory) to set `MACOSX_DEPLOYMENT_TARGET` to the major macOS version: before, that was `10.15`, `10.14`, etc. Now it is `11`, and the next major version will be `12`.
> 
> In any case, `MACOSX_DEPLOYMENT_TARGET=11` is valid and should not lead to failure.

Ok. I understand. At this moment I do not have access to a machine with BigSur. I stuck on the 10.x series. I could create PR with a patch but I cannot test it locally. 
If `MACOSX_DEPLOYMENT_TARGET=11.0` cause build to pass the fix will be short. I only request your help. 

During writing this code it is impossible to predict that Apple will change the numbering scheme. 

But to solve this problem there should be a decision done in the warehouse. Currently, the warehouse will accept `macosx_11_0_x86_64` and decline `macosx_11_x86_64`. As you pointed, it should accept `macosx_11_x86_64`, because `0` is the patch number. And this decision should be made by a proper person from pypa (@agronholm - did you have an idea who should be called)

To prepare the patch I also need some .so or .dylib file to check the results of binary file inspection. 

@fxcoudert If I prepare a patch did you have time to test it?

**Comment by fxcoudert** [comment]
According to https://github.com/pypa/packaging/pull/319#issuecomment-738210958:

> In order to actually remove the minor version we'd have to coordinate with wheel (and maybe create a PEP?) Instead we just pin the minor version to 0.

It seems there is a need for a coordinated discussion about this.

**Comment by Czaki** [comment]
Ok. So I will prepare bugfix patch. But I still have a problem with testing it.

**Comment by ronaldoussoren** [comment]
Please pin the minor version to 0 and treat MACOSX_DEPLOYMENT_TARGET=N as MACOSX_DEPLOYMENT_TARGET=N.0.

There are already wheels for ``macosx_11_0_universal2" on PyPI, and PyPI requires that there is a minor number.

**Comment by fxcoudert** [comment]
@Czaki I can help test, for sure

**Comment by emeryberger** [comment]
The fix in https://github.com/pypa/wheel/commit/e6102e58153fa43089b920e3908eeb908170cf44 only works for Mac x86-64; it still fails on Apple Silicon.

**Comment by agronholm** [comment]
Would vendoring the latest `packaging` help?

**Comment by alphavector** [comment]
> The fix in [e6102e5](https://github.com/pypa/wheel/commit/e6102e58153fa43089b920e3908eeb908170cf44) only works for Mac x86-64; it still fails on Apple Silicon.

@emeryberger, it actually works for Apple Silicon. Some packages will build their own separate dedicated environment with an old wheel version when installed (e.g. numpy). You need to write an issue for each package to make the wheel version >=0.36.1.

**Comment by agronholm** [comment]
I do wonder what reason they have for doing that.

**Comment by gzz2000** [comment]
> I do wonder what reason they have for doing that.

I am building numpy on M1. I succeeded by checking out the newest commit, instead of staying at 1.20.1 release. They seems to have done exactly the same thing: to upgrade wheel, in this commit: https://github.com/numpy/numpy/commit/0a8dca0632185058a4438f792cebf04321212da2

**Comment by mattip** [comment]
The problem is not `wheel`, it is `packaging`. If you do not specify any `packaging` version, you get an older one. I am not sure where it comes from. Maybe `wheel` should specify a dependency on a particular minimum version of `packaging`?

**Comment by gzz2000** [comment]
> The problem is not `wheel`, it is `packaging`. If you do not specify any `packaging` version, you get an older one. I am not sure where it comes from. Maybe `wheel` should specify a dependency on a particular minimum version of `packaging`?

Yes it is packaging. I guess upgrading packaging would also make wheel upgraded. Before upgrading it, I was encountering errors like this, which indicated that it was a wheel version issue:

```
  writing manifest file 'numpy.egg-info/SOURCES.txt'
  Copying numpy.egg-info to build/bdist.macosx-11-arm64/wheel/numpy-1.20.1-py3.9.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 211, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 197, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 513, in <module>
      setup_package()
    File "setup.py", line 505, in setup_package
      setup(**metadata)
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-install-3gtrssd_/numpy_d4eaa76fbd3a463d9624512327629d0d/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 252, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 48, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/private/var/folders/70/cgczdqgs207c849t2v498q580000gp/T/pip-build-env-e_cshiz1/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
      assert len(base_version) == 2
  AssertionError
```

**Comment by agronholm** [comment]
> The problem is not `wheel`, it is `packaging`. If you do not specify any `packaging` version, you get an older one. I am not sure where it comes from. Maybe `wheel` should specify a dependency on a particular minimum version of `packaging`?

Wheel vendors packaging. But the traceback here indicates a problem that has already been fixed in the latest wheel release.

**Comment by arogozhnikov** [comment]
I have M1 and upgraded to newest versions: wheel==0.36.2, packaging==21.0, but still get the same exception when installing scipy (bumpy installed from wheels just in case).

I've also tried running [this](https://github.com/pypa/virtualenv/issues/2027#issuecomment-739147166) one-time command without success.

**Comment by agronholm** [comment]
Are you sure it's actually using the latest wheel? Do other libraries build binary wheels properly? If so, then the culprit is most likely the scientific Python stack with its custom build processes.

**Comment by keleftheriou** [comment]
Possibly related: https://github.com/python/cpython/issues/102362
